source $HOME/.config/nvim/plugin.vim
source $HOME/.config/nvim/basic.vim
source $HOME/.config/nvim/airline.vim
source $HOME/.config/nvim/coc.vim
source $HOME/.config/nvim/coc-fzf.vim
source $HOME/.config/nvim/rainbow.vim
source $HOME/.config/nvim/blamer.vim
source $HOME/.config/nvim/ctrlsf.vim
source $HOME/.config/nvim/mako.vim
